apiVersion: v1
kind: Pod
metadata:
  name: snitch
spec:
  containers:
  - name: snitch
    image: quay.io/pgschk/ingress-snitch:latest
    env:
    - name: TRAEFIK_API_URL
      value: "http://traefik.traefik:9000/api"
    - name: TRAEFIK_NAMESPACE
      value: traefik
    resources:
      requests:
        cpu: 20m
        memory: 20Mi
      limits:
        cpu: 100m
        memory: 50Mi